language: rust
sudo: false

cache: cargo
rust: nightly

install:
  - export CC="gcc-5" CXX="g++-5"
  - curl -LO https://stainless-steel.github.io/travis/bazel.sh && source bazel.sh
  - echo "build --local_resources=1024,0.5,1.0" > ${HOME}/.bazelrc

script:
  - cargo test -vv -j 1
  - cargo run --example=multiplication

after_success:
  - curl https://stainless-steel.github.io/travis/documentation.sh | bash

env:
  global:
    - secure: mwHMtO/K+ZvviCTThxmnc+sbAuYpxkI1cqvx6JhbtiS5KiMlIN2sTrT1RJqa8aSEqBvz+xAc6p9VfGRWMTn888hgz0Vy6IfB1Wgpt2OAi7QuygoqgygKiEHhfE8LtQhO0TMMHyt8WAvkGYSUyfOvYtiQsfRJCJHgxWUSRBgf2JAEOagEPrd5ieA7ASX9Eb1vZ+xagmQV/HEfNtQa7iK7K7PrcXaGbVY4Dho04jOkWf9KWrQ0spTU1bdgO1XfBEKBJTbiT1/MDndRYYb7oiIe/63j3u4xQJzB/tpogWTTPQOslU7tRvFj+K1oLxYMWd4Y6v7jfxE100/nXNC16wK7U2htbaG9ERNNunFPO24iGBMdWeAUokT0aU30kyhMVlFTu7Mg3J0kxMw6JJjoG39LBk0mwe4r7ylorWbaA7XXbwzsv3CO0K7m8QoPozJryOF5mzSht7hvizF0GiM3sOxDZFb5FPHkkrznrLbz29Tp6t/7tUMsZQnv93E3ofg32wyBuC1XEQX5q+hVpBhWdB5B9D9k7gDxEgNoYsJEp0uC/X1P62wbbWr6TYe+KHbqXGgV4uZby3bp+2Ws/h/tc8wFvAw3iTAw64E1/i9s7GQ5uJiKBUbxSrVAL5O9h8uw1m2nAG5+xvOV7opqfEEPGZzFJluCAk1pQI0DT3ACfe9Eo+0=

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-5
      - gcc-5
      - oracle-java8-installer
      - python-numpy
      - swig

notifications:
  email: false
